const $=s=>document.querySelector(s);const svgNS='http://www.w3.org/2000/svg';
const state={people:[],relations:[],zoom:1};let drag=null;
const els={svg:$('#genogram'),nodes:$('#nodeLayer'),relations:$('#relationLayer'),list:$('#peopleList'),empty:$('#emptyState'),personDialog:$('#personDialog'),relationDialog:$('#relationDialog')};
const roleY={조부:120,조모:120,부:310,모:310,대상자:500,배우자:500,자녀:660,'형제·자매':500};
function id(){return crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2)}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function esc(t=''){return t.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function autoPosition(role){const y=roleY[role]||400;const same=state.people.filter(p=>Math.abs(p.y-y)<40).length;return{x:220+same*170,y}}
function save(){localStorage.setItem('genogram-studio',JSON.stringify(state))}
function load(){try{const s=JSON.parse(localStorage.getItem('genogram-studio'));if(s){state.people=s.people||[];state.relations=s.relations||[]}}catch{}render()}
document.querySelectorAll('[data-close="person"]').forEach(b=>b.onclick=()=>els.personDialog.close());document.querySelectorAll('[data-close="relation"]').forEach(b=>b.onclick=()=>els.relationDialog.close());
function activatePanel(panelId){document.querySelectorAll('.mode-tab').forEach(t=>{const active=t.dataset.panel===panelId;t.classList.toggle('active',active);t.setAttribute('aria-selected',String(active))});document.querySelectorAll('.side-panel').forEach(p=>p.classList.toggle('active',p.id===panelId))}
document.querySelectorAll('.mode-tab').forEach(tab=>tab.addEventListener('click',()=>activatePanel(tab.dataset.panel)));
function extraRow(){const row=document.createElement('div');row.className='extra-row';row.innerHTML=`<div class="extra-top"><select class="extra-role" aria-label="가족 관계"><option value="형제·자매">형제·자매</option><option value="조부">조부</option><option value="조모">조모</option><option value="기타 친척">기타 친척</option><option value="보호자·동거인">보호자·동거인</option></select><button type="button" class="remove-extra" aria-label="구성원 삭제">×</button></div><div class="quick-grid"><input class="extra-name" placeholder="식별명" aria-label="식별명"><input class="extra-age" placeholder="나이·출생연도" aria-label="나이"></div><div class="extra-bottom"><select class="extra-gender" aria-label="성별"><option value="unknown">성별 미상</option><option value="male">남성</option><option value="female">여성</option></select><select class="extra-side" aria-label="연결 기준"><option value="child">아동과 같은 세대</option><option value="father">부의 부모 세대</option><option value="mother">모의 부모 세대</option><option value="none">자동 연결 안 함</option></select></div>`;row.querySelector('.remove-extra').onclick=()=>row.remove();row.querySelector('.extra-role').onchange=e=>{if(e.target.value==='조부')row.querySelector('.extra-gender').value='male';if(e.target.value==='조모')row.querySelector('.extra-gender').value='female'};$('#quickExtraList').append(row)}
$('#addExtraBtn').onclick=extraRow;
function toggleParent(checkId,nameId,ageId,cohabitId){const on=$(checkId).checked;[$(nameId),$(ageId),$(cohabitId)].forEach(e=>e.disabled=!on);$(nameId).closest('.parent-block').style.opacity=on?'1':'.45'}
$('#qHasFather').onchange=()=>toggleParent('#qHasFather','#qFatherName','#qFatherAge','#qFatherCohabit');$('#qHasMother').onchange=()=>toggleParent('#qHasMother','#qMotherName','#qMotherAge','#qMotherCohabit');
$('#quickForm').addEventListener('submit',e=>{e.preventDefault();if(state.people.length&&!confirm('현재 가계도를 빠른 작성 내용으로 교체할까요?'))return;const child={id:id(),name:$('#qChildName').value.trim()||'대상아동',role:'대상자',gender:document.querySelector('[name=qChildGender]:checked').value,age:$('#qChildAge').value.trim(),life:'alive',cohabit:'yes',note:'',x:600,y:500};const people=[child],relations=[];let father=null,mother=null;if($('#qHasFather').checked){father={id:id(),name:$('#qFatherName').value.trim()||'부',role:'부',gender:'male',age:$('#qFatherAge').value.trim(),life:'alive',cohabit:$('#qFatherCohabit').checked?'yes':'no',note:'',x:430,y:250};people.push(father);relations.push({id:id(),from:father.id,to:child.id,type:'parent'})}if($('#qHasMother').checked){mother={id:id(),name:$('#qMotherName').value.trim()||'모',role:'모',gender:'female',age:$('#qMotherAge').value.trim(),life:'alive',cohabit:$('#qMotherCohabit').checked?'yes':'no',note:'',x:770,y:250};people.push(mother);relations.push({id:id(),from:mother.id,to:child.id,type:'parent'})}const status=$('#qParentStatus').value;if(father&&mother&&status!=='none')relations.push({id:id(),from:father.id,to:mother.id,type:status});document.querySelectorAll('.extra-row').forEach((row,i)=>{const role=row.querySelector('.extra-role').value,side=row.querySelector('.extra-side').value;const y=side==='child'?610:side==='none'?400:90;const person={id:id(),name:row.querySelector('.extra-name').value.trim()||role,role,gender:row.querySelector('.extra-gender').value,age:row.querySelector('.extra-age').value.trim(),life:'alive',cohabit:'unknown',note:'',x:260+i*145,y};people.push(person);if(side==='child'){if(father)relations.push({id:id(),from:father.id,to:person.id,type:'parent'});if(mother)relations.push({id:id(),from:mother.id,to:person.id,type:'parent'})}if(side==='father'&&father)relations.push({id:id(),from:person.id,to:father.id,type:'parent'});if(side==='mother'&&mother)relations.push({id:id(),from:person.id,to:mother.id,type:'parent'})});state.people=people;state.relations=relations;state.zoom=1;save();render();activatePanel('editPanel');toast('가계도를 만들었습니다. 필요한 부분만 수정하세요')});
function openPerson(person){$('#personForm').reset();$('#personId').value=person?.id||'';$('#personDialogTitle').textContent=person?'구성원 편집':'구성원 추가';if(person){$('#personName').value=person.name;$('#personRole').value=person.role;document.querySelector(`[name=gender][value=${person.gender}]`).checked=true;$('#personAge').value=person.age;$('#personLife').value=person.life;$('#personCohabit').value=person.cohabit;$('#personNote').value=person.note}els.personDialog.showModal();setTimeout(()=>$('#personName').focus(),50)}
$('#personForm').addEventListener('submit',e=>{e.preventDefault();const existing=state.people.find(p=>p.id===$('#personId').value);const role=$('#personRole').value;const data={id:existing?.id||id(),name:$('#personName').value.trim(),role,gender:document.querySelector('[name=gender]:checked').value,age:$('#personAge').value.trim(),life:$('#personLife').value,cohabit:$('#personCohabit').value,note:$('#personNote').value.trim(),...(existing?{x:existing.x,y:existing.y}:autoPosition(role))};if(role==='대상자')state.people.forEach(p=>{if(p.role==='대상자'&&p.id!==data.id)p.role='가족'});if(existing)Object.assign(existing,data);else state.people.push(data);els.personDialog.close();save();render();toast(existing?'구성원 정보를 수정했습니다':'구성원을 추가했습니다')});
function removePerson(pid){if(!confirm('이 구성원과 연결된 관계를 삭제할까요?'))return;state.people=state.people.filter(p=>p.id!==pid);state.relations=state.relations.filter(r=>r.from!==pid&&r.to!==pid);save();render()}
function shapeMarkup(p){const outer=p.role==='대상자'?p.gender==='female'?'<circle class="outer" r="35"/>':'<rect class="outer" x="-35" y="-35" width="70" height="70"/>':'';const shape=p.gender==='female'?'<circle class="shape" r="29"/>':p.gender==='unknown'?'<rect class="shape" x="-22" y="-22" width="44" height="44" transform="rotate(45)"/>':'<rect class="shape" x="-29" y="-29" width="58" height="58"/>';return`${outer}${shape}<path class="death" d="M-23-23L23 23M23-23L-23 23"/>`}
function render(){els.empty.hidden=state.people.length>0;els.list.innerHTML=state.people.map(p=>`<div class="person-card" data-edit="${p.id}"><span class="person-mini ${p.gender}"><span>${p.life==='dead'?'×':''}</span></span><span class="person-copy"><strong>${esc(p.name)}</strong><small>${esc(p.role)} · ${p.age||'연령 미상'}</small></span><button class="card-delete" data-delete="${p.id}" aria-label="삭제">×</button></div>`).join('');els.list.querySelectorAll('[data-edit]').forEach(e=>e.onclick=()=>openPerson(state.people.find(p=>p.id===e.dataset.edit)));els.list.querySelectorAll('[data-delete]').forEach(e=>e.onclick=ev=>{ev.stopPropagation();removePerson(e.dataset.delete)});renderRelations();els.nodes.innerHTML=state.people.map(p=>`<g class="node ${p.role==='대상자'?'proband':''} ${p.life==='dead'?'dead':''}" data-id="${p.id}" transform="translate(${p.x} ${p.y})">${shapeMarkup(p)}<text class="node-label" y="52">${esc(p.name)}</text><text class="node-meta" y="69">${esc(p.role)}${p.age?' · '+esc(p.age):''}</text></g>`).join('');els.nodes.querySelectorAll('.node').forEach(n=>{n.addEventListener('pointerdown',startDrag);n.addEventListener('dblclick',()=>openPerson(state.people.find(p=>p.id===n.dataset.id)))});els.svg.style.transform=`scale(${state.zoom})`;els.svg.style.transformOrigin='center';$('#zoomLabel').textContent=Math.round(state.zoom*100)+'%'}
function zigzag(a,b){const dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy),nx=-dy/len*5,ny=dx/len*5,steps=Math.max(6,Math.floor(len/12));let d=`M${a.x} ${a.y}`;for(let i=1;i<steps;i++){const t=i/steps,s=i%2?1:-1;d+=` L${a.x+dx*t+nx*s} ${a.y+dy*t+ny*s}`}return d+` L${b.x} ${b.y}`}
function renderRelations(){els.relations.innerHTML=state.relations.map(r=>{const a=state.people.find(p=>p.id===r.from),b=state.people.find(p=>p.id===r.to);if(!a||!b)return'';let extra='';if(r.type==='separated'||r.type==='divorced'){const mx=(a.x+b.x)/2,my=(a.y+b.y)/2;extra=`<path d="M${mx-7} ${my-12}l14 24${r.type==='divorced'?`M${mx+2} ${my-12}l14 24`:''}" stroke="#c9002b" stroke-width="2.5"/>`}const d=r.type==='conflict'?zigzag(a,b):`M${a.x} ${a.y} L${b.x} ${b.y}`;return`<g data-relation="${r.id}" class="relation-group"><path class="relation ${r.type}" d="${d}"/>${extra}<circle cx="${(a.x+b.x)/2}" cy="${(a.y+b.y)/2}" r="10" fill="transparent"><title>더블클릭하여 관계 삭제</title></circle></g>`}).join('');els.relations.querySelectorAll('[data-relation]').forEach(g=>g.ondblclick=()=>{state.relations=state.relations.filter(r=>r.id!==g.dataset.relation);save();render();toast('관계를 삭제했습니다')})}
function point(e){const p=els.svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(els.svg.getScreenCTM().inverse())}
function startDrag(e){e.preventDefault();const p=state.people.find(x=>x.id===e.currentTarget.dataset.id),q=point(e);drag={p,dx:q.x-p.x,dy:q.y-p.y};els.svg.setPointerCapture(e.pointerId)}els.svg.addEventListener('pointermove',e=>{if(!drag)return;const q=point(e);drag.p.x=Math.max(55,Math.min(1145,q.x-drag.dx));drag.p.y=Math.max(55,Math.min(665,q.y-drag.dy));renderRelations();const n=els.nodes.querySelector(`[data-id="${drag.p.id}"]`);n.setAttribute('transform',`translate(${drag.p.x} ${drag.p.y})`)});els.svg.addEventListener('pointerup',()=>{if(drag){drag=null;save()}});
function openRelation(){if(state.people.length<2){toast('구성원을 2명 이상 추가해주세요');return}const opts=state.people.map(p=>`<option value="${p.id}">${esc(p.name)} (${esc(p.role)})</option>`).join('');$('#fromPerson').innerHTML=opts;$('#toPerson').innerHTML=opts;$('#toPerson').selectedIndex=1;els.relationDialog.showModal()}
$('#relationForm').addEventListener('submit',e=>{e.preventDefault();const from=$('#fromPerson').value,to=$('#toPerson').value;if(from===to){toast('서로 다른 구성원을 선택해주세요');return}state.relations.push({id:id(),from,to,type:$('#relationType').value});els.relationDialog.close();save();render();toast('관계를 연결했습니다')});
function setZoom(v){state.zoom=Math.max(.65,Math.min(1.45,v));render()}$('#zoomInBtn').onclick=()=>setZoom(state.zoom+.1);$('#zoomOutBtn').onclick=()=>setZoom(state.zoom-.1);$('#fitBtn').onclick=()=>setZoom(1);$('#relationBtn').onclick=openRelation;$('#addPersonBtn').onclick=()=>openPerson();$('#canvasAddBtn').onclick=()=>{activatePanel('editPanel');openPerson()};$('#emptyAddBtn').onclick=()=>{activatePanel('quickPanel');$('#qChildName').focus()};
$('#resetBtn').onclick=()=>{if(state.people.length&&!confirm('현재 가계도를 모두 지우고 새로 시작할까요?'))return;state.people=[];state.relations=[];save();render()};
$('#downloadBtn').onclick=()=>{if(!state.people.length){toast('저장할 가계도가 없습니다');return}const clone=els.svg.cloneNode(true);clone.style.transform='';clone.setAttribute('width','1200');clone.setAttribute('height','720');const css=document.createElementNS(svgNS,'style');css.textContent='.node .shape{fill:white;stroke:#33272a;stroke-width:3}.node .outer{fill:none;stroke:#c9002b;stroke-width:3}.node .death{stroke:#c9002b;stroke-width:3}.node-label{font:600 14px sans-serif;fill:#241b1d;text-anchor:middle}.node-meta{font:11px sans-serif;fill:#746a6c;text-anchor:middle}.relation{fill:none;stroke:#5c5053;stroke-width:2.5}.relation.close{stroke-width:6}.relation.distant{stroke-dasharray:8 7}.relation.conflict{stroke:#c9002b}';clone.prepend(css);const xml=new XMLSerializer().serializeToString(clone),img=new Image(),url=URL.createObjectURL(new Blob([xml],{type:'image/svg+xml'}));img.onload=()=>{const c=document.createElement('canvas');c.width=2400;c.height=1440;const ctx=c.getContext('2d');ctx.scale(2,2);ctx.drawImage(img,0,0);URL.revokeObjectURL(url);c.toBlob(blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`가계도_${new Date().toISOString().slice(0,10)}.png`;a.click();URL.revokeObjectURL(a.href);toast('PNG 파일로 저장했습니다')},'image/png')};img.src=url};
load();
