(() => {
  const svg=document.querySelector('#combinedMap');if(!svg)return;
  const q=s=>document.querySelector(s),key='case-relationship-studio-combined-v1',familyLayer=q('#combinedFamilyLayer'),relationLayer=q('#combinedRelationLayer'),resourceLayer=q('#combinedResourceLayer');
  const fresh=()=>({resources:[],selected:null,familyOffset:{x:0,y:0}});let combined=fresh(),resourceClickTimer=null,drag=null,suppressClick=false;
  try{const saved=JSON.parse(localStorage.getItem(key));if(saved&&Array.isArray(saved.resources))combined={...fresh(),...saved,familyOffset:saved.familyOffset||{x:0,y:0}}}catch{}
  const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch])),uid=()=>`cr-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`,save=()=>localStorage.setItem(key,JSON.stringify(combined));
  function familyState(){try{return typeof state!=='undefined'?state:JSON.parse(localStorage.getItem('genogram-studio'))||{people:[],relations:[]}}catch{return{people:[],relations:[]}}}
  function selected(){return combined.resources.find(item=>item.id===combined.selected)}function offset(){return combined.familyOffset||(combined.familyOffset={x:0,y:0})}
  function defaultPosition(index,total){const o=offset(),angle=-Math.PI/2+index*Math.PI*2/Math.max(6,total),radius=315;return{x:700+o.x+Math.cos(angle)*radius,y:365+o.y+Math.sin(angle)*radius}}
  function ensurePositions(){combined.resources.forEach((item,index)=>{if(!Number.isFinite(item.x)||!Number.isFinite(item.y))Object.assign(item,defaultPosition(index,combined.resources.length))})}
  function targetPoint(target){const data=familyState(),person=data.people.find(p=>p.id===target),o=offset();return person?{x:170+o.x+Number(person.x||600)*.78,y:70+o.y+Number(person.y||360)*.78}:{x:638+o.x,y:350+o.y}}
  function point(event){const p=svg.createSVGPoint();p.x=event.clientX;p.y=event.clientY;return p.matrixTransform(svg.getScreenCTM().inverse())}
  function wrap(text,max=18){const value=String(text||'').trim();if(!value)return[];const lines=[];for(let i=0;i<value.length;i+=max)lines.push(value.slice(i,i+max));return lines.slice(0,2)}
  function targetOptions(){const data=familyState(),select=q('#combinedTarget'),current=selected()?.target||'family';select.innerHTML='<option value="family">가족 전체</option>'+data.people.map(p=>`<option value="${esc(p.id)}">${esc(p.name)} · ${esc(p.role)}</option>`).join('');select.value=[...select.options].some(o=>o.value===current)?current:'family';if(selected())selected().target=select.value}
  function renderFamily(){const data=familyState(),sourceRelations=document.querySelector('#relationLayer'),sourceNodes=document.querySelector('#nodeLayer');if(!data.people.length){familyLayer.innerHTML='<text class="combined-empty" x="700" y="350">가계도 탭에서 구성원을 먼저 만들어주세요</text>';return}const o=offset();familyLayer.innerHTML=`<text class="combined-zone-title" x="34" y="38">통합 관계도</text><text class="combined-zone-caption" x="112" y="38">가계도와 자원을 같은 그리드에서 자유롭게 배치하세요</text><g class="combined-family-copy" transform="translate(${170+o.x} ${70+o.y}) scale(.78)"><g>${sourceRelations?.innerHTML||''}</g><g>${sourceNodes?.innerHTML||''}</g></g>`;familyLayer.querySelectorAll('.node[data-id]').forEach(node=>{node.classList.add('combined-targetable');node.classList.toggle('combined-target-selected',selected()?.target===node.dataset.id);node.onclick=()=>{if(drag||suppressClick)return;const item=selected();if(!item)return;item.target=node.dataset.id;save();render()}})}
  function editResource(node){const item=combined.resources.find(r=>r.id===node.dataset.resourceId);if(!item||typeof openResourceGridEditor!=='function')return;openResourceGridEditor(item,next=>{item.name=next.name;item.memo=next.memo;save();render()})}
  function render(){ensurePositions();renderFamily();targetOptions();const active=selected(),disabled=!active;q('#combinedSelectedLabel').textContent=active?`${active.name} 연결 설정`:'자원을 선택하세요';['#combinedTarget','#combinedStrength','#combinedDirection','#combinedDeleteResource'].forEach(sel=>q(sel).disabled=disabled);if(active){q('#combinedTarget').value=active.target||'family';q('#combinedStrength').value=active.strength;q('#combinedDirection').value=active.direction}
    q('#combinedResourceList').innerHTML=combined.resources.length?combined.resources.map(r=>`<button type="button" class="eco-list-item ${r.id===combined.selected?'active':''}" data-combined-resource="${r.id}"><i></i><span><b>${esc(r.name)}</b><small>${esc(r.memo||'메모 없음')}</small></span><span>${esc((familyState().people.find(p=>p.id===r.target)?.name)||'가족 전체')}</span></button>`).join(''):'<p class="relation-empty">등록된 자원이 없습니다.</p>';q('#combinedResourceList').querySelectorAll('[data-combined-resource]').forEach(button=>button.onclick=()=>{combined.selected=button.dataset.combinedResource;save();render()});
    resourceLayer.innerHTML=(combined.resources.length?'':'<text class="combined-empty" x="700" y="675">왼쪽에서 자원을 추가하면 가계도 주변에 배치됩니다</text>')+combined.resources.map(r=>{const lines=wrap(r.memo||'메모 없음');return`<g class="combined-resource ${r.id===combined.selected?'selected':''}" data-resource-id="${r.id}" transform="translate(${r.x} ${r.y})"><rect x="-92" y="-39" width="184" height="78" rx="10"/><text class="resource-edit-control" x="82" y="-25" text-anchor="end">✎ 수정</text><text class="resource-name" y="-11">${esc(r.name)}</text><line x1="-78" y1="2" x2="78" y2="2" class="resource-divider"/><text class="resource-note" y="18">${lines.map((line,index)=>`<tspan x="0" dy="${index?13:0}">${esc(line)}</tspan>`).join('')}</text></g>`}).join('');resourceLayer.querySelectorAll('[data-resource-id]').forEach(node=>{node.onclick=event=>{if(event.target.closest('.resource-edit-control')){clearTimeout(resourceClickTimer);event.stopPropagation();editResource(node);return}clearTimeout(resourceClickTimer);resourceClickTimer=setTimeout(()=>{combined.selected=node.dataset.resourceId;save();render()},220)};node.ondblclick=event=>{clearTimeout(resourceClickTimer);event.preventDefault();event.stopPropagation();editResource(node)}});
    relationLayer.innerHTML=combined.resources.map(r=>{const to=targetPoint(r.target),dx=to.x-r.x,dy=to.y-r.y,len=Math.max(1,Math.hypot(dx,dy)),ux=dx/len,uy=dy/len,start={x:r.x+ux*96,y:r.y+uy*42},end={x:to.x-ux*44,y:to.y-uy*44},marker=r.direction==='both'?'marker-start="url(#combinedArrow)" marker-end="url(#combinedArrow)"':r.direction==='in'?'marker-end="url(#combinedArrow)"':r.direction==='out'?'marker-start="url(#combinedArrow)"':'';return`<path class="combined-resource-line ${r.strength}" d="M${start.x} ${start.y} L${end.x} ${end.y}" ${marker}/>`}).join('')}
  q('#combinedResourceForm').addEventListener('submit',event=>{event.preventDefault();const name=q('#combinedResourceName').value.trim();if(!name)return;const pos=defaultPosition(combined.resources.length,combined.resources.length+1),item={id:uid(),name,target:'family',strength:'normal',direction:'both',memo:'',x:pos.x,y:pos.y};combined.resources.push(item);combined.selected=item.id;q('#combinedResourceName').value='';save();render()});
  q('#combinedTarget').onchange=e=>{const item=selected();if(item){item.target=e.target.value;save();render()}};q('#combinedStrength').onchange=e=>{const item=selected();if(item){item.strength=e.target.value;save();render()}};q('#combinedDirection').onchange=e=>{const item=selected();if(item){item.direction=e.target.value;save();render()}};
  q('#combinedDeleteResource').onclick=()=>{const item=selected();if(!item||!confirm(`${item.name} 자원을 삭제할까요?`))return;combined.resources=combined.resources.filter(r=>r.id!==item.id);combined.selected=null;save();render()};q('#combinedResetBtn').onclick=()=>{if(combined.resources.length&&!confirm('종합 관계도의 자원과 메모를 모두 지울까요? 가계도는 유지됩니다.'))return;combined=fresh();save();render()};
  q('#combinedGoGenogram').onclick=()=>document.querySelector('[data-studio-mode="genogram"]')?.click();q('#combinedRefreshBtn').onclick=()=>render();q('#combinedAutoArrange').onclick=()=>{combined.resources.forEach((item,index)=>Object.assign(item,defaultPosition(index,combined.resources.length)));save();render();if(typeof toast==='function')toast('가계도 주변으로 자원을 자동 배치했습니다')};
  svg.addEventListener('pointerdown',event=>{if(event.target.closest('.resource-edit-control'))return;suppressClick=false;const p=point(event),resourceNode=event.target.closest('.combined-resource'),familyNode=event.target.closest('.combined-family-copy .node');if(resourceNode){const item=combined.resources.find(r=>r.id===resourceNode.dataset.resourceId);if(!item)return;combined.selected=item.id;drag={type:'resource',item,dx:p.x-item.x,dy:p.y-item.y,pointerId:event.pointerId};svg.setPointerCapture(event.pointerId)}else if(familyNode){const o=offset();drag={type:'family',dx:p.x-o.x,dy:p.y-o.y,pointerId:event.pointerId};svg.setPointerCapture(event.pointerId)}});svg.addEventListener('pointermove',event=>{if(!drag||event.pointerId!==drag.pointerId)return;suppressClick=true;const p=point(event);if(drag.type==='resource'){drag.item.x=Math.max(105,Math.min(1295,p.x-drag.dx));drag.item.y=Math.max(75,Math.min(685,p.y-drag.dy))}else{combined.familyOffset={x:Math.max(-120,Math.min(300,p.x-drag.dx)),y:Math.max(-50,Math.min(150,p.y-drag.dy))}}render()});const endDrag=event=>{if(!drag||(event.pointerId!=null&&event.pointerId!==drag.pointerId))return;drag=null;save();setTimeout(()=>{suppressClick=false},0)};svg.addEventListener('pointerup',endDrag);svg.addEventListener('pointercancel',endDrag);
  q('#combinedDownloadBtn').onclick=()=>{const clone=svg.cloneNode(true);clone.querySelector('.combined-grid')?.remove();clone.setAttribute('width','1400');clone.setAttribute('height','760');const style=document.createElementNS('http://www.w3.org/2000/svg','style');style.textContent='text{font-family:sans-serif}.combined-zone-title{font-weight:700;font-size:12px}.combined-zone-caption{font-size:9px;fill:#888}.combined-resource rect{fill:#fff;stroke:#555;stroke-width:2}.resource-name{text-anchor:middle;font-weight:700;font-size:12px}.resource-note{text-anchor:middle;font-size:8px;fill:#777}.resource-divider{stroke:#e1d6d9}.resource-edit-control{display:none}.combined-resource-line{fill:none;stroke:#555;stroke-width:2.5}.combined-resource-line.strong{stroke-width:6}.combined-resource-line.weak{stroke-dasharray:8 7}.combined-resource-line.stress{stroke:#c9002b}.node-label{text-anchor:middle;font-weight:700}.node-meta{text-anchor:middle;fill:#88797d}.relation{fill:none}';clone.querySelector('defs')?.append(style);const source=new XMLSerializer().serializeToString(clone),blob=new Blob([source],{type:'image/svg+xml'}),url=URL.createObjectURL(blob),img=new Image();img.onload=()=>{const canvas=document.createElement('canvas');canvas.width=2800;canvas.height=1520;const ctx=canvas.getContext('2d');ctx.scale(2,2);ctx.fillStyle='#fff';ctx.fillRect(0,0,1400,760);ctx.drawImage(img,0,0,1400,760);URL.revokeObjectURL(url);const a=document.createElement('a');a.download=`가계도_생태도_종합_${new Date().toISOString().slice(0,10)}.png`;a.href=canvas.toDataURL('image/png');a.click();if(typeof toast==='function')toast('종합 관계도를 PNG로 저장했습니다')};img.src=url};document.addEventListener('studio-mode-change',event=>{if(event.detail?.mode==='combined')render()});render();
})();
