(() => {
  const svg=document.querySelector('#combinedMap');
  if(!svg)return;
  const q=s=>document.querySelector(s),key='case-relationship-studio-combined-v1';
  const familyLayer=q('#combinedFamilyLayer'),relationLayer=q('#combinedRelationLayer'),resourceLayer=q('#combinedResourceLayer'),memoLayer=q('#combinedMemoLayer');
  const categories={protection:{label:'아동보호·공공기관',color:'#c9002b'},education:{label:'학교·보육',color:'#236a8d'},health:{label:'의료·정신건강',color:'#3d7d67'},welfare:{label:'복지·경제·주거',color:'#956d24'},legal:{label:'경찰·법률',color:'#654a86'},family:{label:'친족·이웃·지지자',color:'#7b5f68'},community:{label:'지역사회·여가',color:'#7b6b37'}};
  const fresh=()=>({resources:[],selected:null});let combined=fresh();
  try{const saved=JSON.parse(localStorage.getItem(key));if(saved&&Array.isArray(saved.resources))combined=saved;}catch{}
  const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const uid=()=>`cr-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
  const save=()=>localStorage.setItem(key,JSON.stringify(combined));
  function familyState(){try{return typeof state!=='undefined'?state:JSON.parse(localStorage.getItem('genogram-studio'))||{people:[],relations:[]};}catch{return{people:[],relations:[]}}}
  function selected(){return combined.resources.find(item=>item.id===combined.selected)}
  function resourcePosition(index,total){if(total<=6)return{x:1215,y:145+index*88};const col=index%2,row=Math.floor(index/2);return{x:1135+col*165,y:145+row*88}}
  function targetPoint(target){const data=familyState(),person=data.people.find(p=>p.id===target);return person?{x:80+Number(person.x||600)*.76,y:92+Number(person.y||360)*.76}:{x:540,y:380}}
  function wrap(text,max=32){const value=String(text||'').trim();if(!value)return[];const lines=[];for(let i=0;i<value.length;i+=max)lines.push(value.slice(i,i+max));return lines.slice(0,2)}
  function targetOptions(){const data=familyState(),select=q('#combinedTarget'),current=selected()?.target||'family';select.innerHTML='<option value="family">가족 전체</option>'+data.people.map(p=>`<option value="${esc(p.id)}">${esc(p.name)} · ${esc(p.role)}</option>`).join('');select.value=[...select.options].some(o=>o.value===current)?current:'family';if(selected())selected().target=select.value}
  function renderFamily(){
    const data=familyState(),sourceRelations=document.querySelector('#relationLayer'),sourceNodes=document.querySelector('#nodeLayer');
    if(!data.people.length){familyLayer.innerHTML='<rect class="combined-map-zone" x="40" y="52" width="990" height="650" rx="18"/><text class="combined-zone-title" x="68" y="82">가계도 영역</text><text class="combined-empty" x="535" y="360">가계도 탭에서 구성원을 먼저 만들어주세요</text>';return}
    familyLayer.innerHTML=`<rect class="combined-map-zone" x="40" y="52" width="990" height="650" rx="18"/><text class="combined-zone-title" x="68" y="82">가계도 영역</text><text class="combined-zone-caption" x="153" y="82">자원을 선택한 뒤 구성원을 누르면 바로 연결됩니다</text><g class="combined-family-copy" transform="translate(80 92) scale(.76)"><g>${sourceRelations?.innerHTML||''}</g><g>${sourceNodes?.innerHTML||''}</g></g>`;
    familyLayer.querySelectorAll('.node[data-id]').forEach(node=>{node.classList.add('combined-targetable');node.classList.toggle('combined-target-selected',selected()?.target===node.dataset.id);node.onclick=()=>{const item=selected();if(!item)return;if(!data.people.some(p=>p.id===node.dataset.id))return;item.target=node.dataset.id;save();render()}});
  }
  function render(){
    renderFamily();targetOptions();const active=selected(),disabled=!active;
    q('#combinedSelectedLabel').textContent=active?`${active.name} 연결 설정`:'자원을 선택하세요';['#combinedTarget','#combinedStrength','#combinedDirection','#combinedMemo','#combinedDeleteResource'].forEach(sel=>q(sel).disabled=disabled);
    if(active){q('#combinedTarget').value=active.target||'family';q('#combinedStrength').value=active.strength;q('#combinedDirection').value=active.direction;q('#combinedMemo').value=active.memo||''}
    q('#combinedResourceList').innerHTML=combined.resources.length?combined.resources.map(r=>`<button type="button" class="eco-list-item ${r.id===combined.selected?'active':''}" data-combined-resource="${r.id}" style="--eco-color:${categories[r.category]?.color}"><i></i><span><b>${esc(r.name)}</b><small>${esc(categories[r.category]?.label)}</small></span><span>${esc((familyState().people.find(p=>p.id===r.target)?.name)||'가족 전체')}</span></button>`).join(''):'<p class="relation-empty">등록된 자원이 없습니다.</p>';
    q('#combinedResourceList').querySelectorAll('[data-combined-resource]').forEach(button=>button.onclick=()=>{combined.selected=button.dataset.combinedResource;save();render()});
    const total=combined.resources.length;
    resourceLayer.innerHTML=`<rect class="combined-map-zone resource" x="1050" y="52" width="320" height="650" rx="18"/><text class="combined-zone-title" x="1078" y="82">자원 영역</text><text class="combined-zone-caption" x="1148" y="82">기관·사람·서비스</text>${total?'':'<text class="combined-empty" x="1210" y="360">왼쪽에서 자원을 추가하세요</text>'}`+combined.resources.map((r,i)=>{const p=resourcePosition(i,total),cat=categories[r.category]||categories.community;return`<g class="combined-resource ${r.id===combined.selected?'selected':''}" data-resource-id="${r.id}" style="--resource-color:${cat.color}" transform="translate(${p.x} ${p.y})"><rect x="-70" y="-31" width="140" height="62" rx="10"/><text class="resource-name" y="-3">${esc(r.name)}</text><text class="resource-category" y="14">${esc(cat.label)}</text></g>`}).join('');
    resourceLayer.querySelectorAll('[data-resource-id]').forEach(node=>node.onclick=()=>{combined.selected=node.dataset.resourceId;save();render()});
    relationLayer.innerHTML=combined.resources.map((r,i)=>{const p=resourcePosition(i,total),to=targetPoint(r.target),marker=r.direction==='both'?'marker-start="url(#combinedArrow)" marker-end="url(#combinedArrow)"':r.direction==='in'?'marker-end="url(#combinedArrow)"':r.direction==='out'?'marker-start="url(#combinedArrow)"':'';return`<path class="combined-resource-line ${r.strength}" d="M${p.x-72} ${p.y} C${p.x-185} ${p.y},${to.x+135} ${to.y},${to.x} ${to.y}" ${marker}/>`}).join('');
    const notes=combined.resources.filter(r=>r.memo?.trim());memoLayer.innerHTML=`<rect class="combined-map-zone memo" x="40" y="722" width="1330" height="150" rx="18"/><text class="combined-zone-title" x="68" y="752">메모 영역</text><text class="combined-zone-caption" x="138" y="752">자원별 확인 내용 · 관계도와 분리 표시</text>`+(notes.length?'':'<text class="combined-empty" x="705" y="815">선택한 자원에 메모를 입력하면 이곳에 따로 표시됩니다</text>')+notes.slice(0,6).map((r,i)=>{const col=i%3,row=Math.floor(i/3),x=68+col*430,y=770+row*48,lines=wrap(r.memo);return`<g class="combined-memo-card"><rect x="${x}" y="${y}" width="402" height="40" rx="8"/><text class="memo-owner" x="${x+12}" y="${y+15}">${esc(r.name)}</text><text class="memo-copy" x="${x+12}" y="${y+30}">${esc(lines.join(' · '))}</text></g>`}).join('');
  }
  q('#combinedResourceForm').addEventListener('submit',event=>{event.preventDefault();const name=q('#combinedResourceName').value.trim();if(!name)return;const item={id:uid(),name,category:q('#combinedResourceCategory').value,target:'family',strength:'normal',direction:'both',memo:''};combined.resources.push(item);combined.selected=item.id;q('#combinedResourceName').value='';save();render()});
  q('#combinedTarget').onchange=e=>{const item=selected();if(item){item.target=e.target.value;save();render()}};
  q('#combinedStrength').onchange=e=>{const item=selected();if(item){item.strength=e.target.value;save();render()}};
  q('#combinedDirection').onchange=e=>{const item=selected();if(item){item.direction=e.target.value;save();render()}};
  q('#combinedMemo').oninput=e=>{const item=selected();if(item){item.memo=e.target.value;save();render()}};
  q('#combinedDeleteResource').onclick=()=>{const item=selected();if(!item||!confirm(`${item.name} 자원을 삭제할까요?`))return;combined.resources=combined.resources.filter(r=>r.id!==item.id);combined.selected=null;save();render()};
  q('#combinedResetBtn').onclick=()=>{if(combined.resources.length&&!confirm('종합 관계도의 자원과 메모를 모두 지울까요? 가계도는 유지됩니다.'))return;combined=fresh();save();render()};
  q('#combinedGoGenogram').onclick=()=>document.querySelector('[data-studio-mode="genogram"]')?.click();q('#combinedRefreshBtn').onclick=()=>render();q('#combinedAutoArrange').onclick=()=>{render();if(typeof toast==='function')toast('자원과 메모를 영역별로 정리했습니다')};
  q('#combinedDownloadBtn').onclick=()=>{const clone=svg.cloneNode(true);clone.querySelector('.combined-grid')?.remove();clone.setAttribute('width','1400');clone.setAttribute('height','900');const style=document.createElementNS('http://www.w3.org/2000/svg','style');style.textContent='text{font-family:sans-serif}.combined-map-zone{fill:#fff;stroke:#ddd}.combined-map-zone.resource{fill:#faf7f8}.combined-map-zone.memo{fill:#fff8e9}.combined-zone-title{font-weight:700;font-size:12px}.combined-zone-caption{font-size:9px;fill:#888}.combined-resource rect{fill:#fff;stroke:#555;stroke-width:2}.resource-name{text-anchor:middle;font-weight:700;font-size:12px}.resource-category{text-anchor:middle;font-size:8px;fill:#777}.combined-resource-line{fill:none;stroke:#555;stroke-width:2.5}.combined-resource-line.strong{stroke-width:6}.combined-resource-line.weak{stroke-dasharray:8 7}.combined-resource-line.stress{stroke:#c9002b}.combined-memo-card rect{fill:#fffdf7;stroke:#dfc985}.memo-owner{font-size:9px;font-weight:700;fill:#8a6820}.memo-copy{font-size:9px}.node-label{text-anchor:middle;font-weight:700}.node-meta{text-anchor:middle;fill:#88797d}.relation{fill:none}';clone.querySelector('defs')?.append(style);const source=new XMLSerializer().serializeToString(clone),blob=new Blob([source],{type:'image/svg+xml'}),url=URL.createObjectURL(blob),img=new Image();img.onload=()=>{const canvas=document.createElement('canvas');canvas.width=2800;canvas.height=1800;const ctx=canvas.getContext('2d');ctx.scale(2,2);ctx.fillStyle='#fff';ctx.fillRect(0,0,1400,900);ctx.drawImage(img,0,0,1400,900);URL.revokeObjectURL(url);const a=document.createElement('a');a.download=`가계도_생태도_종합_${new Date().toISOString().slice(0,10)}.png`;a.href=canvas.toDataURL('image/png');a.click();if(typeof toast==='function')toast('종합 관계도를 PNG로 저장했습니다')};img.src=url};
  document.addEventListener('studio-mode-change',event=>{if(event.detail?.mode==='combined')render()});render();
})();
