(() => {
  const svg=document.querySelector('#ecomap'),nodeLayer=document.querySelector('#ecoNodeLayer'),relationLayer=document.querySelector('#ecoRelationLayer');
  if(!svg||!nodeLayer||!relationLayer)return;
  const q=s=>document.querySelector(s),key='case-relationship-studio-ecomap-v1';
  const strengthNames={strong:'강한 지지',normal:'일반·보통',weak:'약함·취약',stress:'긴장·갈등'};
  const directionNames={both:'상호 교류',in:'가족에게 유입',out:'가족에서 외부로 제공',none:'방향 없음'};
  const fresh=()=>({center:{name:'피해아동 및 가족',x:550,y:350},systems:[],selected:null});
  let state=fresh(),drag=null,editClickTimer=null;
  try{const saved=JSON.parse(localStorage.getItem(key));if(saved?.center&&Array.isArray(saved.systems))state=saved;}catch{}
  const makeId=()=>crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function save(){localStorage.setItem(key,JSON.stringify(state));}
  function selected(){return state.systems.find(item=>item.id===state.selected);}
  function point(event){const p=svg.createSVGPoint();p.x=event.clientX;p.y=event.clientY;return p.matrixTransform(svg.getScreenCTM().inverse());}
  function clippedPoints(system){const c=state.center,dx=system.x-c.x,dy=system.y-c.y,len=Math.max(1,Math.hypot(dx,dy)),ux=dx/len,uy=dy/len;return{a:{x:c.x+ux*86,y:c.y+uy*86},b:{x:system.x-ux*82,y:system.y-uy*42}};}
  function zigzag(a,b){const dx=b.x-a.x,dy=b.y-a.y,len=Math.max(1,Math.hypot(dx,dy)),nx=-dy/len*5,ny=dx/len*5,steps=Math.max(7,Math.floor(len/15));let d=`M${a.x} ${a.y}`;for(let i=1;i<steps;i++){const t=i/steps,s=i%2?1:-1;d+=` L${a.x+dx*t+nx*s} ${a.y+dy*t+ny*s}`;}return d+` L${b.x} ${b.y}`;}
  function arrows(direction){if(direction==='both')return'marker-start="url(#ecoArrow)" marker-end="url(#ecoArrow)"';if(direction==='in')return'marker-start="url(#ecoArrow)"';if(direction==='out')return'marker-end="url(#ecoArrow)"';return'';}
  function relationMarkup(system){const {a,b}=clippedPoints(system),straight=`M${a.x} ${a.y} L${b.x} ${b.y}`,d=system.strength==='stress'?zigzag(a,b):straight;return`<g class="eco-relation-group" data-eco-relation="${system.id}"><path class="eco-relation ${system.strength}" d="${d}" ${arrows(system.direction)}/><path class="eco-relation-hit" d="${d}"/></g>`;}
  function textMarkup(name,y){const value=String(name||'이름 없음');if(value.length<=11)return`<text class="eco-name" y="${y}">${esc(value)}</text>`;const cut=Math.min(11,Math.ceil(value.length/2));return`<text class="eco-name" y="${y-8}"><tspan x="0">${esc(value.slice(0,cut))}</tspan><tspan x="0" dy="17">${esc(value.slice(cut,22))}</tspan></text>`;}
  function nodeMarkup(system){const note=String(system.note||'').trim(),lines=note?[note.slice(0,20),note.slice(20,40)].filter(Boolean):['더블클릭해 메모 입력'];return`<g class="eco-node system ${state.selected===system.id?'selected':''}" data-eco-node="${system.id}" transform="translate(${system.x} ${system.y})"><rect x="-86" y="-45" width="172" height="90" rx="11" fill="#fff" stroke="#5f5256" stroke-width="3"/>${textMarkup(system.name,-13)}<line x1="-70" y1="5" x2="70" y2="5" class="eco-table-divider" stroke="#e5dadd"/><text class="eco-resource-note" y="22" fill="#786b6f" text-anchor="middle" font-size="9">${lines.map((line,index)=>`<tspan x="0" dy="${index?14:0}">${esc(line)}</tspan>`).join('')}</text></g>`;}
  function render(){
    relationLayer.innerHTML=state.systems.map(relationMarkup).join('');
    nodeLayer.innerHTML=`<g class="eco-node center" data-eco-center transform="translate(${state.center.x} ${state.center.y})"><circle r="84"/>${textMarkup(state.center.name,-3)}<text class="eco-category" y="29">중심체계</text></g>${state.systems.map(nodeMarkup).join('')}${state.systems.length?'':`<text class="eco-empty-label" x="550" y="485">왼쪽에서 환경체계를 추가하면 이곳에 표시됩니다</text>`}`;
    const system=selected(),strength=q('#ecoRelationStrength'),direction=q('#ecoRelationDirection'),del=q('#ecoDeleteSystem');
    [strength,direction,del].forEach(el=>{if(el)el.disabled=!system;});
    q('#ecoSelectedSystemLabel').textContent=system?`${system.name} 연결 설정`:'환경체계를 선택하세요';
    if(system){strength.value=system.strength;direction.value=system.direction;}
    q('#ecoCenterName').value=state.center.name;
    q('#ecoSystemList').innerHTML=state.systems.length?state.systems.map(item=>`<button type="button" class="eco-list-item ${state.selected===item.id?'active':''}" data-eco-list="${item.id}"><i></i><span><b>${esc(item.name)}</b><small>${esc(item.note||'메모 없음')}</small></span><span>${strengthNames[item.strength]}</span></button>`).join(''):'<div class="eco-list-item"><i></i><span><b>등록된 환경체계가 없습니다</b><small>위 입력창이나 빠른 추가를 사용하세요</small></span></div>';
  }
  function choose(id){state.selected=id;render();save();}
  function addSystem(name){name=String(name||'').trim();if(!name)return;const count=state.systems.length,angle=-Math.PI/2+count*(Math.PI*2/Math.max(6,count+1)),radius=count<8?245:305;const item={id:makeId(),name,strength:'normal',direction:'both',note:'',x:state.center.x+Math.cos(angle)*radius,y:state.center.y+Math.sin(angle)*radius};state.systems.push(item);state.selected=item.id;save();render();}
  function autoArrange(){const n=state.systems.length;if(!n)return;const radius=n<=7?245:Math.min(310,220+n*7);state.systems.forEach((item,index)=>{const angle=-Math.PI/2+index*Math.PI*2/n;item.x=state.center.x+Math.cos(angle)*radius;item.y=state.center.y+Math.sin(angle)*radius;});save();render();}
  q('#ecoSystemForm').addEventListener('submit',event=>{event.preventDefault();addSystem(q('#ecoSystemName').value);q('#ecoSystemName').value='';q('#ecoSystemName').focus();});
  document.querySelectorAll('[data-eco-preset]').forEach(button=>button.addEventListener('click',()=>{const name=button.dataset.ecoPreset;if(state.systems.some(item=>item.name===name)){choose(state.systems.find(item=>item.name===name).id);return;}addSystem(name);}));
  q('#ecoCenterName').addEventListener('input',event=>{state.center.name=event.target.value.trim()||'피해아동 및 가족';save();render();});
  q('#ecoRelationStrength').addEventListener('change',event=>{const item=selected();if(!item)return;item.strength=event.target.value;save();render();});
  q('#ecoRelationDirection').addEventListener('change',event=>{const item=selected();if(!item)return;item.direction=event.target.value;save();render();});
  q('#ecoDeleteSystem').addEventListener('click',()=>{const item=selected();if(!item||!confirm(`${item.name} 환경체계를 삭제할까요?`))return;state.systems=state.systems.filter(system=>system.id!==item.id);state.selected=null;save();render();});
  q('#ecoSystemList').addEventListener('click',event=>{const button=event.target.closest('[data-eco-list]');if(button)choose(button.dataset.ecoList);});
  relationLayer.addEventListener('click',event=>{const group=event.target.closest('[data-eco-relation]');if(group)choose(group.dataset.ecoRelation);});
  svg.addEventListener('pointerdown',event=>{const node=event.target.closest('.eco-node');if(!node)return;event.preventDefault();const p=point(event),item=node.hasAttribute('data-eco-center')?state.center:state.systems.find(system=>system.id===node.dataset.ecoNode);if(!item)return;if(node.dataset.ecoNode){state.selected=node.dataset.ecoNode;nodeLayer.querySelectorAll('.eco-node.system').forEach(el=>el.classList.toggle('selected',el===node));}drag={item,dx:p.x-item.x,dy:p.y-item.y,pointerId:event.pointerId};svg.setPointerCapture(event.pointerId);});
  svg.addEventListener('click',event=>{const node=event.target.closest('.eco-node.system');if(!node)return;clearTimeout(editClickTimer);editClickTimer=setTimeout(()=>choose(node.dataset.ecoNode),220)});
  svg.addEventListener('dblclick',event=>{const node=event.target.closest('.eco-node.system');if(!node)return;clearTimeout(editClickTimer);event.preventDefault();const item=state.systems.find(system=>system.id===node.dataset.ecoNode);if(!item||typeof openResourceGridEditor!=='function')return;openResourceGridEditor(item,next=>{item.name=next.name;item.note=next.memo;save();render()})});
  svg.addEventListener('pointermove',event=>{if(!drag||event.pointerId!==drag.pointerId)return;const p=point(event);drag.item.x=Math.max(90,Math.min(1010,p.x-drag.dx));drag.item.y=Math.max(90,Math.min(610,p.y-drag.dy));render();});
  const endDrag=event=>{if(!drag||(event.pointerId!=null&&event.pointerId!==drag.pointerId))return;drag=null;save();};svg.addEventListener('pointerup',endDrag);svg.addEventListener('pointercancel',endDrag);
  q('#ecoAutoArrange').addEventListener('click',autoArrange);
  q('#ecoResetBtn').addEventListener('click',()=>{if(!confirm('현재 생태도 작업을 모두 지우고 새로 만들까요?'))return;state=fresh();save();render();});
  q('#ecoDownloadBtn').addEventListener('click',()=>{const clone=svg.cloneNode(true);clone.querySelector('.eco-grid')?.remove();clone.querySelectorAll('.eco-relation-hit').forEach(el=>el.remove());clone.setAttribute('width','1100');clone.setAttribute('height','700');const exportStyle=document.createElementNS('http://www.w3.org/2000/svg','style');exportStyle.textContent='.eco-node circle{fill:#fff;stroke:var(--eco-color,#5f5256);stroke-width:3}.eco-node.center circle{fill:#fff5f7;stroke:#c9002b;stroke-width:4}.eco-name{font:700 14px sans-serif;fill:#302528;text-anchor:middle}.eco-category{font:500 10px sans-serif;fill:#85777b;text-anchor:middle}.eco-relation{fill:none;stroke:#5d5054;stroke-width:2.5}.eco-relation.strong{stroke-width:6}.eco-relation.weak{stroke-dasharray:8 7}.eco-relation.stress{stroke:#c9002b;stroke-width:3}';clone.querySelector('defs')?.append(exportStyle);const source=new XMLSerializer().serializeToString(clone),blob=new Blob([source],{type:'image/svg+xml'}),url=URL.createObjectURL(blob),img=new Image();img.onload=()=>{const canvas=document.createElement('canvas');canvas.width=2200;canvas.height=1400;const ctx=canvas.getContext('2d');ctx.scale(2,2);ctx.fillStyle='#fff';ctx.fillRect(0,0,1100,700);ctx.drawImage(img,0,0,1100,700);URL.revokeObjectURL(url);const link=document.createElement('a');link.download=`생태도_${new Date().toISOString().slice(0,10)}.png`;link.href=canvas.toDataURL('image/png');link.click();if(typeof toast==='function')toast('생태도를 PNG로 저장했습니다');};img.src=url;});
  render();
})();
